SignalRWebApp/Models/BANGGIATRUCTUYEN.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
namespace SignalRWebApp.Models
{
    [Serializable]
    [DataContract(IsReference = true)]
    public class BANGGIATRUCTUYEN : EntityBase
    {
        [DataMember]
        [Display(Name = "Mã CP")]
        public string MACP { get; set; }

        [DataMember]
        [Display(Name = "Mua 3")]
        public double? GIAMUA3 { get; set; }

        [DataMember]
        [Display(Name = "KL 3")]
        public int? KLMUA3 { get; set; }

       
        [DataMember]
        [Display(Name = "Mua 2")]
        public double? GIAMUA2 { get; set; }

        [DataMember]
        [Display(Name = "KL 2")]
        public int? KLMUA2 { get; set; }

        [DataMember]
        [Display(Name = "Mua 1")]
        public double? GIAMUA1 { get; set; }

        [DataMember]
        [Display(Name = "KL 1")]
        public int? KLMUA1 { get; set; }

        [DataMember]
        [Display(Name = "giá Khớp")]
        public double? KHOPLENHGIA { get; set; }

        [DataMember]
        [Display(Name = "KL Khớp")]
        public int? KHOPLENHKL { get; set; }

        [DataMember]
        [Display(Name = "Bán 1")]
        public double? GIABAN1 { get; set; }

        [DataMember]
        [Display(Name = "KL B 1")]
        public int? KLBAN1 { get; set; }

        [DataMember]
        [Display(Name = "Bán 2")]
        public double? GIABAN2 { get; set; }

        [DataMember]
        [Display(Name = "KL B 2")]
        public int? KLBAN2 { get; set; }

        [DataMember]
        [Display(Name = "Bán 3")]
        public double? GIABAN3 { get; set; }

        [DataMember]
        [Display(Name = "KL B 3")]
        public int? KLBAN3 { get; set; }

        [DataMember]
        [Display(Name = "TỔNG KL")]
        public int? TONG { get; set; }




    }

}

SignalRWebApp/Controllers/BANGGIATRUCTUYENController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SignalRWebApp.Models;
using SignalRWebApp.SqlServerNotifier;

namespace SignalRWebApp.Controllers
{
    public class BANGGIATRUCTUYENController : Controller
    {
        private BANGGIATRUCTUYENcontext db = new BANGGIATRUCTUYENcontext();

        public async Task<ActionResult> Index()
        {
            var collection = db.BANGGIATRUCTUYENs;
            ViewBag.NotifierEntity = db.GetNotifierEntity<BANGGIATRUCTUYEN>(collection).ToJson();
            return View(await collection.ToListAsync());
        }

        public async Task<ActionResult> IndexPartial()
        {
            var collection = db.BANGGIATRUCTUYENs;
            ViewBag.NotifierEntity = db.GetNotifierEntity<BANGGIATRUCTUYEN>(collection).ToJson();
            return PartialView(await collection.ToListAsync());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SignalRWebApp/Views/BANGGIATRUCTUYEN/Index.cshtml
@model IEnumerable<SignalRWebApp.Models.BANGGIATRUCTUYEN>

@{
    ViewBag.Title = "BẢNG GIÁ TRỰC TUYẾN";
}

<h2 style="text-align:center">BẢNG GIÁ TRỰC TUYẾN</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<div id="tbs" class="table table-bordered">
    @Html.Partial("IndexPartial", Model)
</div>

@section scripts {

    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>

    <script type="text/javascript">
        var signalRHubInitialized = false;

        $(function () {
            InitializeSignalRHubStore();
        });

        function InitializeSignalRHubStore() {

            if (signalRHubInitialized)
                return;

            try {
                var clientHub = $.connection.bANGGIATRUCTUYENHub;
                alert(clientHub);

                clientHub.client.broadcastMessage = function (message) {
                    if (message === "Refresh")
                        ReloadIndexPartial();
                };

                $.connection.hub.start().done(function () {
                    clientHub.server.initialize($("#NotifierEntity").val());
                    signalRHubInitialized = true;
                });

            } catch (err) {
                signalRHubInitialized = false;
            }
        };

        function ReloadIndexPartial() {
          //  alert("load ra")
            $.post('@(Url.Action("IndexPartial", "BANGGIATRUCTUYEN", null, Request.Url.Scheme))')
                .done(function (response) {
                    $("#tbs").html(response)
                    if (!signalRHubInitialized)
                        InitializeSignalRHubStore();
                });
        };
    </script>

}

SignalRWebApp/Views/BANGGIATRUCTUYEN/IndexPartial.cshtml
@model IEnumerable<SignalRWebApp.Models.BANGGIATRUCTUYEN>

@Html.Hidden("NotifierEntity", (object)ViewBag.NotifierEntity)

<table class="table">
    <tr>
        <th rowspan="2" style="text-align:center; background-color red"> @Html.DisplayNameFor(model => model.MACP)</th>
        <th colspan="6" style="text-align:center">BÊN BÁN</th>
        <th colspan="2" style="text-align:center">KHỚP LỆNH</th>
        <th colspan="6" style="text-align:center">BÊN MUA</th>
        <th rowspan="2" style="text-align:center"> @Html.DisplayNameFor(model => model.TONG)</th>

    </tr>
    <tr>

        <th class="table-success">
            @Html.DisplayNameFor(model => model.GIAMUA3)
        </th>
        <th class="table-success">
            @Html.DisplayNameFor(model => model.KLMUA3)
        </th>
        <th class="table-success">
            @Html.DisplayNameFor(model => model.GIAMUA2)
        </th>
        <th class="table-success">
            @Html.DisplayNameFor(model => model.KLMUA2)
        </th>
        <th class="table-success">
            @Html.DisplayNameFor(model => model.GIAMUA1)
        </th>
        <th class="table-success">
            @Html.DisplayNameFor(model => model.KLMUA1)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.KHOPLENHGIA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KHOPLENHKL)
        </th>
    
        <th>
            @Html.DisplayNameFor(model => model.GIABAN1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KLBAN1)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.GIABAN2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KLBAN2)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.GIABAN3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KLBAN3)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MACP)
            </td>

            <th>
                @Html.DisplayFor(modelItem => item.GIAMUA3)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KLMUA3)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.GIAMUA2)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KLMUA2)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.GIAMUA1)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KLMUA1)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KHOPLENHGIA)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KHOPLENHKL)
            </th>

            <th>
                @Html.DisplayFor(modelItem => item.GIABAN1)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KLBAN1)
            </th>

            <th>
                @Html.DisplayFor(modelItem => item.GIABAN2)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KLBAN2)
            </th>

            <th>
                @Html.DisplayFor(modelItem => item.GIABAN3)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.KLBAN3)
            </th>

            <th>
                @Html.DisplayFor(modelItem => item.TONG)
            </th>


        </tr>
    }

</table>